source 'https://rubygems.org'

gem 'unicorn'
gem 'platform_sh', '0.2.6.pre'
gem 'sinatra'
gem 'mysql2'
gem 'redis'
gem 'elasticsearch'
gem 'sunspot'
gem 'bunny'
gem 'mongo'
gem 'pg'
gem 'activerecord'
gem 'influxdb'
